# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rag.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'rag.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trag.proto\x12\x08rbac_rag\"q\n\x10RetrievalRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x19\n\x11\x61llowed_asset_ids\x18\x03 \x03(\t\x12\"\n\x07\x63ontext\x18\x04 \x03(\x0b\x32\x11.rbac_rag.Message\"(\n\x07Message\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"7\n\x11RetrievalResponse\x12\"\n\x06\x63hunks\x18\x01 \x03(\x0b\x32\x12.rbac_rag.Document\"\x94\x01\n\x08\x44ocument\x12\x14\n\x0cpage_content\x18\x01 \x01(\t\x12\x32\n\x08metadata\x18\x02 \x03(\x0b\x32 .rbac_rag.Document.MetadataEntry\x12\r\n\x05score\x18\x03 \x01(\x02\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32Z\n\nRagService\x12L\n\x11RetrieveDocuments\x12\x1a.rbac_rag.RetrievalRequest\x1a\x1b.rbac_rag.RetrievalResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rag_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DOCUMENT_METADATAENTRY']._loaded_options = None
  _globals['_DOCUMENT_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_RETRIEVALREQUEST']._serialized_start=23
  _globals['_RETRIEVALREQUEST']._serialized_end=136
  _globals['_MESSAGE']._serialized_start=138
  _globals['_MESSAGE']._serialized_end=178
  _globals['_RETRIEVALRESPONSE']._serialized_start=180
  _globals['_RETRIEVALRESPONSE']._serialized_end=235
  _globals['_DOCUMENT']._serialized_start=238
  _globals['_DOCUMENT']._serialized_end=386
  _globals['_DOCUMENT_METADATAENTRY']._serialized_start=339
  _globals['_DOCUMENT_METADATAENTRY']._serialized_end=386
  _globals['_RAGSERVICE']._serialized_start=388
  _globals['_RAGSERVICE']._serialized_end=478
# @@protoc_insertion_point(module_scope)
