---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: data
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: __ECR_FRONTEND_IMAGE__
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: NEXT_PUBLIC_AUTH_API_URL
              value: "/api"
            - name: NEXT_PUBLIC_CHAT_API_URL
              value: "/api"
            - name: NEXT_PUBLIC_WS_URL
              value: "ws://localhost/ws"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: data
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
