---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-status-service
  namespace: data
  labels:
    app: task-status-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-status-service
  template:
    metadata:
      labels:
        app: task-status-service
    spec:
      containers:
        - name: task-status-service
          image: __ECR_TASK_STATUS_IMAGE__
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              value: "3002"
            - name: RABBITMQ_URL
              value: "amqp://admin:admin@rabbitmq.data.svc.cluster.local:5672"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 3
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: task-status-service
  namespace: data
spec:
  selector:
    app: task-status-service
  ports:
    - name: http
      port: 3002
      targetPort: 3002
