apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-agent1
  namespace: data
  labels:
    app: worker-agent1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-agent1
  template:
    metadata:
      labels:
        app: worker-agent1
    spec:
      containers:
        - name: worker-agent1
          image: __ECR_AGENT1_IMAGE__
          imagePullPolicy: Always
          env:
            - name: RABBITMQ_URL
              value: "amqp://admin:admin@rabbitmq.data.svc.cluster.local:5672"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
