import os
import glob
import subprocess
import re

def main():
    print("Starting Automated Migration Compression...")

    # 1. Wipe existing migrations
    versions_dir = os.path.join("alembic", "versions")
    print("1. Deleting existing migration files...")
    for f in glob.glob(os.path.join(versions_dir, "*.py")):
        os.remove(f)
        print(f"   Deleted {f}")

    # 2. Drop and recreate the local database
    print("2. Wiping local database to create a clean baseline...")
    # Use sys.executable to run drop_db.py
    import sys
    subprocess.run([sys.executable, "-m", "scripts.drop_db"], check=True)

    # 3. Generate the new baseline migration
    print("3. Generating new unified baseline migration...")
    subprocess.run([sys.executable, "-m", "alembic", "revision", "--autogenerate", "--rev-id", "001", "-m", "initial_schema"], check=True)

    # Find the newly generated file
    new_files = glob.glob(os.path.join(versions_dir, "*_initial_schema.py"))
    if not new_files:
        print("Error: Alembic failed to generate a new migration file.")
        return
    migration_file = new_files[0]
    print(f"Found new migration file: {migration_file}")

    # 4 & 5. Inject required imports and vector extension
    print("4. Injecting missing SQLModel/PGVector imports and CREATE EXTENSION command...")
    with open(migration_file, "r") as f:
        content = f.read()

    # Add imports
    imports_to_add = """
import sqlmodel
import pgvector
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql
"""
    if "import sqlmodel" not in content:
        content = re.sub(
            r"(import sqlalchemy as sa)",
            r"\1\n" + imports_to_add.strip(),
            content
        )

    # Add vector extension to upgrade()
    vector_extension_sql = "    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')\n"
    if "CREATE EXTENSION" not in content:
        content = re.sub(
            r"(def upgrade\(\) -> None:\n(?:.|\n)*?# ### commands auto generated by Alembic - please adjust! ###\n)",
            r"\1" + vector_extension_sql,
            content
        )

    with open(migration_file, "w") as f:
        f.write(content)
        
    print("Migration compression complete!")
    print("You can now safely run: alembic upgrade head")

if __name__ == "__main__":
    main()
