"""add_cascade_deletes

Revision ID: 056
Revises: 055
Create Date: 2026-06-18 12:12:33.026981

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import pgvector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '056'
down_revision: Union[str, Sequence[str], None] = '055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('irs_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('s3_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('irs_rule_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('irs_rule_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['irs_rule_id'], ['irs_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('agent_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('agent_tasks', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_constraint(op.f('agent_tasks_org_id_fkey'), 'agent_tasks', type_='foreignkey')
    op.drop_constraint(op.f('agent_tasks_user_id_fkey'), 'agent_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'agent_tasks', 'orgs', ['org_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'agent_tasks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('api_execution_logs', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('api_execution_logs', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('ix_api_execution_logs_proposal'), table_name='api_execution_logs')
    op.create_index(op.f('ix_api_execution_logs_proposal_id'), 'api_execution_logs', ['proposal_id'], unique=False)
    op.drop_constraint(op.f('api_execution_logs_api_module_id_fkey'), 'api_execution_logs', type_='foreignkey')
    op.create_foreign_key(None, 'api_execution_logs', 'api_modules', ['api_module_id'], ['id'], ondelete='CASCADE')
    op.alter_column('api_modules', 'name',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('api_modules', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('api_modules', 'base_url',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('api_modules', 'endpoint_path',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('api_modules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('api_modules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_api_modules_org_enabled'), table_name='api_modules')
    op.alter_column('api_task_proposals', 'title',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('api_task_proposals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('api_task_proposals', 'decided_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('ix_api_task_proposals_session'), table_name='api_task_proposals')
    op.drop_index(op.f('ix_api_task_proposals_status'), table_name='api_task_proposals')
    op.create_index(op.f('ix_api_task_proposals_chat_session_id'), 'api_task_proposals', ['chat_session_id'], unique=False)
    op.drop_constraint(op.f('api_task_proposals_agent_task_id_fkey'), 'api_task_proposals', type_='foreignkey')
    op.drop_constraint(op.f('api_task_proposals_api_module_id_fkey'), 'api_task_proposals', type_='foreignkey')
    op.create_foreign_key(None, 'api_task_proposals', 'agent_tasks', ['agent_task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'api_task_proposals', 'api_modules', ['api_module_id'], ['id'], ondelete='CASCADE')
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_constraint(op.f('audit_logs_org_id_fkey'), 'audit_logs', type_='foreignkey')
    op.drop_constraint(op.f('audit_logs_user_id_fkey'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'orgs', ['org_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_constraint(op.f('chat_messages_chat_id_fkey'), 'chat_messages', type_='foreignkey')
    op.drop_constraint(op.f('chat_messages_org_id_fkey'), 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'chat_sessions', ['chat_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chat_messages', 'orgs', ['org_id'], ['id'], ondelete='CASCADE')
    op.alter_column('chat_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_constraint(op.f('chat_sessions_org_id_fkey'), 'chat_sessions', type_='foreignkey')
    op.drop_constraint(op.f('chat_sessions_user_id_fkey'), 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'chat_sessions', 'orgs', ['org_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chat_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('cost_seg_rulesets', 'workflow_type',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False,
               existing_server_default=sa.text("'cost_seg'::text"))
    op.alter_column('cost_seg_rulesets', 'filename',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('cost_seg_rulesets', 'size_bytes',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('cost_seg_rulesets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_cost_seg_rulesets_workflow_type'), table_name='cost_seg_rulesets')
    op.alter_column('document_chunks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index(op.f('document_chunks_embedding_idx'), table_name='document_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_constraint(op.f('document_chunks_image_id_fkey'), 'document_chunks', type_='foreignkey')
    op.drop_constraint(op.f('document_chunks_document_id_fkey'), 'document_chunks', type_='foreignkey')
    op.drop_constraint(op.f('document_chunks_org_id_fkey'), 'document_chunks', type_='foreignkey')
    op.create_foreign_key(None, 'document_chunks', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'document_chunks', 'document_images', ['image_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'document_chunks', 'orgs', ['org_id'], ['id'], ondelete='CASCADE')
    op.alter_column('document_images', 'content_hash',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='SHA-256 hash of image bytes',
               existing_nullable=True)
    op.alter_column('document_images', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_document_images_document_id'), table_name='document_images')
    op.drop_constraint(op.f('document_images_org_id_fkey'), 'document_images', type_='foreignkey')
    op.create_foreign_key(None, 'document_images', 'orgs', ['org_id'], ['id'], ondelete='CASCADE')
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index(op.f('ix_documents_session_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_tags_gin'), table_name='documents', postgresql_using='gin')
    op.drop_constraint(op.f('documents_org_id_fkey'), 'documents', type_='foreignkey')
    op.drop_constraint(op.f('documents_session_id_fkey'), 'documents', type_='foreignkey')
    op.drop_constraint(op.f('documents_uploaded_by_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'users', ['uploaded_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'documents', 'orgs', ['org_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'documents', 'workflow_sessions', ['session_id'], ['id'], ondelete='SET NULL')
    op.alter_column('invite_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('invite_tokens', 'used_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('invite_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('master_modules', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('master_modules', 'permission_keys',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String(length=100)),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('master_modules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('master_modules_parent_id_fkey'), 'master_modules', type_='foreignkey')
    op.create_foreign_key(None, 'master_modules', 'master_modules', ['parent_id'], ['id'])
    op.drop_constraint(op.f('oauth_identities_user_id_fkey'), 'oauth_identities', type_='foreignkey')
    op.create_foreign_key(None, 'oauth_identities', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('org_memberships', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index(op.f('uq_org_memberships_user_org'), table_name='org_memberships')
    op.create_index(op.f('ix_org_memberships_user_id'), 'org_memberships', ['user_id'], unique=False)
    op.drop_constraint(op.f('org_memberships_user_id_fkey'), 'org_memberships', type_='foreignkey')
    op.drop_constraint(op.f('org_memberships_org_id_fkey'), 'org_memberships', type_='foreignkey')
    op.create_foreign_key(None, 'org_memberships', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'org_memberships', 'orgs', ['org_id'], ['id'], ondelete='CASCADE')
    op.alter_column('org_modules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_org_modules_org_module'), 'org_modules', type_='unique')
    op.create_index(op.f('ix_org_modules_module_id'), 'org_modules', ['module_id'], unique=False)
    op.drop_constraint(op.f('org_prompts_org_id_fkey'), 'org_prompts', type_='foreignkey')
    op.create_foreign_key(None, 'org_prompts', 'orgs', ['org_id'], ['id'], ondelete='CASCADE')
    op.alter_column('orgs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('permissions', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_permissions_resource_action'), 'permissions', type_='unique')
    op.create_index(op.f('ix_permissions_action'), 'permissions', ['action'], unique=False)
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.alter_column('refresh_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_constraint(op.f('refresh_tokens_org_id_fkey'), 'refresh_tokens', type_='foreignkey')
    op.drop_constraint(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'orgs', ['org_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('role_org_permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_role_org_permissions_role_org_permission'), 'role_org_permissions', type_='unique')
    op.create_index(op.f('ix_role_org_permissions_permission_id'), 'role_org_permissions', ['permission_id'], unique=False)
    op.drop_constraint(op.f('fk_role_org_permissions_role_id_roles'), 'role_org_permissions', type_='foreignkey')
    op.drop_constraint(op.f('fk_role_org_permissions_permission_id_permissions'), 'role_org_permissions', type_='foreignkey')
    op.drop_constraint(op.f('fk_role_org_permissions_org_id_orgs'), 'role_org_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'role_org_permissions', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'role_org_permissions', 'permissions', ['permission_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'role_org_permissions', 'orgs', ['org_id'], ['id'], ondelete='CASCADE')
    op.alter_column('role_permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_role_permissions_role_permission'), 'role_permissions', type_='unique')
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.drop_constraint(op.f('fk_role_permissions_role_id_roles'), 'role_permissions', type_='foreignkey')
    op.drop_constraint(op.f('fk_role_permissions_permission_id_permissions'), 'role_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'role_permissions', 'permissions', ['permission_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'role_permissions', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.alter_column('roles', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_roles_is_system'), table_name='roles')
    op.drop_index(op.f('ix_roles_organization_id'), table_name='roles')
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.drop_constraint(op.f('fk_roles_organization_id_orgs'), 'roles', type_='foreignkey')
    op.create_foreign_key(None, 'roles', 'orgs', ['organization_id'], ['id'], ondelete='CASCADE')
    op.alter_column('super_admin_allowlist', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('super_admin_allowlist', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('web_urls', 'url',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('web_urls', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('web_urls', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('workflow_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_constraint(op.f('workflow_items_session_id_fkey'), 'workflow_items', type_='foreignkey')
    op.drop_constraint(op.f('workflow_items_org_id_fkey'), 'workflow_items', type_='foreignkey')
    op.create_foreign_key(None, 'workflow_items', 'workflow_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'workflow_items', 'orgs', ['org_id'], ['id'], ondelete='CASCADE')
    op.alter_column('workflow_outputs', 'generated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_workflow_outputs_session_type'), 'workflow_outputs', type_='unique')
    op.drop_constraint(op.f('workflow_outputs_session_id_fkey'), 'workflow_outputs', type_='foreignkey')
    op.drop_constraint(op.f('workflow_outputs_org_id_fkey'), 'workflow_outputs', type_='foreignkey')
    op.create_foreign_key(None, 'workflow_outputs', 'workflow_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'workflow_outputs', 'orgs', ['org_id'], ['id'], ondelete='CASCADE')
    op.alter_column('workflow_sessions', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('workflow_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_constraint(op.f('workflow_sessions_user_id_fkey'), 'workflow_sessions', type_='foreignkey')
    op.drop_constraint(op.f('workflow_sessions_org_id_fkey'), 'workflow_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'workflow_sessions', 'orgs', ['org_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'workflow_sessions', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflow_sessions', type_='foreignkey')
    op.drop_constraint(None, 'workflow_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('workflow_sessions_org_id_fkey'), 'workflow_sessions', 'orgs', ['org_id'], ['id'])
    op.create_foreign_key(op.f('workflow_sessions_user_id_fkey'), 'workflow_sessions', 'users', ['user_id'], ['id'])
    op.alter_column('workflow_sessions', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('workflow_sessions', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'workflow_outputs', type_='foreignkey')
    op.drop_constraint(None, 'workflow_outputs', type_='foreignkey')
    op.create_foreign_key(op.f('workflow_outputs_org_id_fkey'), 'workflow_outputs', 'orgs', ['org_id'], ['id'])
    op.create_foreign_key(op.f('workflow_outputs_session_id_fkey'), 'workflow_outputs', 'workflow_sessions', ['session_id'], ['id'])
    op.create_unique_constraint(op.f('uq_workflow_outputs_session_type'), 'workflow_outputs', ['session_id', 'type'], postgresql_nulls_not_distinct=False)
    op.alter_column('workflow_outputs', 'generated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_constraint(None, 'workflow_items', type_='foreignkey')
    op.drop_constraint(None, 'workflow_items', type_='foreignkey')
    op.create_foreign_key(op.f('workflow_items_org_id_fkey'), 'workflow_items', 'orgs', ['org_id'], ['id'])
    op.create_foreign_key(op.f('workflow_items_session_id_fkey'), 'workflow_items', 'workflow_sessions', ['session_id'], ['id'])
    op.alter_column('workflow_items', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('web_urls', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('web_urls', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('web_urls', 'url',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('super_admin_allowlist', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('super_admin_allowlist', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.create_foreign_key(op.f('fk_roles_organization_id_orgs'), 'roles', 'orgs', ['organization_id'], ['id'])
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.create_index(op.f('ix_roles_organization_id'), 'roles', ['organization_id'], unique=False)
    op.create_index(op.f('ix_roles_is_system'), 'roles', ['is_system'], unique=False)
    op.alter_column('roles', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('roles', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_role_permissions_permission_id_permissions'), 'role_permissions', 'permissions', ['permission_id'], ['id'])
    op.create_foreign_key(op.f('fk_role_permissions_role_id_roles'), 'role_permissions', 'roles', ['role_id'], ['id'])
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.create_unique_constraint(op.f('uq_role_permissions_role_permission'), 'role_permissions', ['role_id', 'permission_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('role_permissions', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'role_org_permissions', type_='foreignkey')
    op.drop_constraint(None, 'role_org_permissions', type_='foreignkey')
    op.drop_constraint(None, 'role_org_permissions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_role_org_permissions_org_id_orgs'), 'role_org_permissions', 'orgs', ['org_id'], ['id'])
    op.create_foreign_key(op.f('fk_role_org_permissions_permission_id_permissions'), 'role_org_permissions', 'permissions', ['permission_id'], ['id'])
    op.create_foreign_key(op.f('fk_role_org_permissions_role_id_roles'), 'role_org_permissions', 'roles', ['role_id'], ['id'])
    op.drop_index(op.f('ix_role_org_permissions_permission_id'), table_name='role_org_permissions')
    op.create_unique_constraint(op.f('uq_role_org_permissions_role_org_permission'), 'role_org_permissions', ['role_id', 'org_id', 'permission_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('role_org_permissions', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('refresh_tokens_org_id_fkey'), 'refresh_tokens', 'orgs', ['org_id'], ['id'])
    op.alter_column('refresh_tokens', 'expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_action'), table_name='permissions')
    op.create_unique_constraint(op.f('uq_permissions_resource_action'), 'permissions', ['resource', 'action'], postgresql_nulls_not_distinct=False)
    op.alter_column('permissions', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('permissions', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('orgs', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_constraint(None, 'org_prompts', type_='foreignkey')
    op.create_foreign_key(op.f('org_prompts_org_id_fkey'), 'org_prompts', 'orgs', ['org_id'], ['id'])
    op.drop_index(op.f('ix_org_modules_module_id'), table_name='org_modules')
    op.create_unique_constraint(op.f('uq_org_modules_org_module'), 'org_modules', ['org_id', 'module_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('org_modules', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'org_memberships', type_='foreignkey')
    op.drop_constraint(None, 'org_memberships', type_='foreignkey')
    op.create_foreign_key(op.f('org_memberships_org_id_fkey'), 'org_memberships', 'orgs', ['org_id'], ['id'])
    op.create_foreign_key(op.f('org_memberships_user_id_fkey'), 'org_memberships', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_org_memberships_user_id'), table_name='org_memberships')
    op.create_index(op.f('uq_org_memberships_user_org'), 'org_memberships', ['user_id', 'org_id'], unique=True)
    op.alter_column('org_memberships', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_constraint(None, 'oauth_identities', type_='foreignkey')
    op.create_foreign_key(op.f('oauth_identities_user_id_fkey'), 'oauth_identities', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'master_modules', type_='foreignkey')
    op.create_foreign_key(op.f('master_modules_parent_id_fkey'), 'master_modules', 'master_modules', ['parent_id'], ['id'], ondelete='SET NULL')
    op.alter_column('master_modules', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('master_modules', 'permission_keys',
               existing_type=postgresql.ARRAY(sa.String(length=100)),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('master_modules', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('invite_tokens', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('invite_tokens', 'used_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('invite_tokens', 'expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_uploaded_by_fkey'), 'documents', 'users', ['uploaded_by'], ['id'])
    op.create_foreign_key(op.f('documents_session_id_fkey'), 'documents', 'workflow_sessions', ['session_id'], ['id'])
    op.create_foreign_key(op.f('documents_org_id_fkey'), 'documents', 'orgs', ['org_id'], ['id'])
    op.create_index(op.f('ix_documents_tags_gin'), 'documents', ['tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_documents_session_id'), 'documents', ['session_id'], unique=False)
    op.alter_column('documents', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_constraint(None, 'document_images', type_='foreignkey')
    op.create_foreign_key(op.f('document_images_org_id_fkey'), 'document_images', 'orgs', ['org_id'], ['id'])
    op.create_index(op.f('idx_document_images_document_id'), 'document_images', ['document_id'], unique=False)
    op.alter_column('document_images', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_images', 'content_hash',
               existing_type=sa.VARCHAR(length=64),
               comment='SHA-256 hash of image bytes',
               existing_nullable=True)
    op.drop_constraint(None, 'document_chunks', type_='foreignkey')
    op.drop_constraint(None, 'document_chunks', type_='foreignkey')
    op.drop_constraint(None, 'document_chunks', type_='foreignkey')
    op.create_foreign_key(op.f('document_chunks_org_id_fkey'), 'document_chunks', 'orgs', ['org_id'], ['id'])
    op.create_foreign_key(op.f('document_chunks_document_id_fkey'), 'document_chunks', 'documents', ['document_id'], ['id'])
    op.create_foreign_key(op.f('document_chunks_image_id_fkey'), 'document_chunks', 'document_images', ['image_id'], ['id'])
    op.create_index(op.f('document_chunks_embedding_idx'), 'document_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('document_chunks', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_cost_seg_rulesets_workflow_type'), 'cost_seg_rulesets', ['workflow_type'], unique=False)
    op.alter_column('cost_seg_rulesets', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cost_seg_rulesets', 'size_bytes',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('cost_seg_rulesets', 'filename',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('cost_seg_rulesets', 'workflow_type',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'cost_seg'::text"))
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('chat_sessions_user_id_fkey'), 'chat_sessions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('chat_sessions_org_id_fkey'), 'chat_sessions', 'orgs', ['org_id'], ['id'])
    op.alter_column('chat_sessions', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key(op.f('chat_messages_org_id_fkey'), 'chat_messages', 'orgs', ['org_id'], ['id'])
    op.create_foreign_key(op.f('chat_messages_chat_id_fkey'), 'chat_messages', 'chat_sessions', ['chat_id'], ['id'])
    op.alter_column('chat_messages', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_user_id_fkey'), 'audit_logs', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('audit_logs_org_id_fkey'), 'audit_logs', 'orgs', ['org_id'], ['id'])
    op.alter_column('audit_logs', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_constraint(None, 'api_task_proposals', type_='foreignkey')
    op.drop_constraint(None, 'api_task_proposals', type_='foreignkey')
    op.create_foreign_key(op.f('api_task_proposals_api_module_id_fkey'), 'api_task_proposals', 'api_modules', ['api_module_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('api_task_proposals_agent_task_id_fkey'), 'api_task_proposals', 'agent_tasks', ['agent_task_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_api_task_proposals_chat_session_id'), table_name='api_task_proposals')
    op.create_index(op.f('ix_api_task_proposals_status'), 'api_task_proposals', ['status'], unique=False)
    op.create_index(op.f('ix_api_task_proposals_session'), 'api_task_proposals', ['chat_session_id'], unique=False)
    op.alter_column('api_task_proposals', 'decided_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('api_task_proposals', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('api_task_proposals', 'title',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('ix_api_modules_org_enabled'), 'api_modules', ['org_id', 'enabled'], unique=False)
    op.alter_column('api_modules', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('api_modules', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('api_modules', 'endpoint_path',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('api_modules', 'base_url',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('api_modules', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('api_modules', 'name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'api_execution_logs', type_='foreignkey')
    op.create_foreign_key(op.f('api_execution_logs_api_module_id_fkey'), 'api_execution_logs', 'api_modules', ['api_module_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_api_execution_logs_proposal_id'), table_name='api_execution_logs')
    op.create_index(op.f('ix_api_execution_logs_proposal'), 'api_execution_logs', ['proposal_id'], unique=False)
    op.alter_column('api_execution_logs', 'completed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('api_execution_logs', 'started_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'agent_tasks', type_='foreignkey')
    op.drop_constraint(None, 'agent_tasks', type_='foreignkey')
    op.create_foreign_key(op.f('agent_tasks_user_id_fkey'), 'agent_tasks', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('agent_tasks_org_id_fkey'), 'agent_tasks', 'orgs', ['org_id'], ['id'])
    op.alter_column('agent_tasks', 'completed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('agent_tasks', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_table('irs_rule_chunks')
    op.drop_table('irs_rules')
    # ### end Alembic commands ###
